include:
  - /git-deploy/.gitlab-ci.yml

#

variables:
  # CI variables
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  GIT_STRATEGY: fetch

  # Globals
  DOCKER_VERSION: "18"

  KUBECTL_VERSION: "1.0"
  GIT_DEPLOY_VERSION: "1.0"
  GIT_TAG_RELEASE_VERSION: "1.0"
  HELM_VERSION: "1.3"
  CURL_VERSION: "1.0"
  INFRA_ANSIBLE_CI_VERSION: "1.0"

.register_image_stage: &register_image_stage
  image: docker:18
  variables:
    DOCKER_HOST: tcp://localhost:2375
  only:
    - master
  services:
    - docker:18-dind
  before_script:
    - docker login  $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN

stages:
  - "Build"
  - "Test"
  - "Release"

#

Release:
  stage: "Release"
  image: node:10-alpine
  only:
    - master
  when: manual
  before_script:
    - git checkout ${CI_COMMIT_REF_NAME}
    - git config user.name "Social Groovy Bot"
    - git config user.email "45039513+SocialGroovyBot@users.noreply.github.com"
    - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CI_PROJECT_PATH}.git
  script:
    - npx semantic-release

#

.base_register_to_gitlab_stage:
  image: docker:${DOCKER_VERSION}
  services:
    - docker:${DOCKER_VERSION}-dind
  before_script:
    - echo "${CI_JOB_TOKEN}" | docker login ${CI_REGISTRY} -u gitlab-ci-token --password-stdin
  script:
    - >
      if [[ -n "${CI_COMMIT_TAG}" ]]; then
        export TAG=$(printf "${CI_COMMIT_TAG}" | sed "s/^v//")
      else
        export TAG=${CI_COMMIT_REF_SLUG}
      fi
    #
    - docker pull ${IMAGE_NAME}:${CI_COMMIT_BEFORE_SHA} || true
    - docker pull ${IMAGE_NAME}:${TAG} || true
    - docker pull ${IMAGE_NAME}:master || true
    - echo ">  docker build ${DOCKER_BUILD_ARGS} --cache-from ${IMAGE_NAME}:${CI_COMMIT_BEFORE_SHA} --cache-from ${IMAGE_NAME}:$TAG --cache-from ${IMAGE_NAME}:master -t ${IMAGE_NAME}:$CI_COMMIT_SHA -t ${IMAGE_NAME}:${TAG} ${CONTEXT}"
    - docker build ${DOCKER_BUILD_ARGS} --cache-from ${IMAGE_NAME}:${CI_COMMIT_BEFORE_SHA} --cache-from ${IMAGE_NAME}:$TAG --cache-from ${IMAGE_NAME}:master -t ${IMAGE_NAME}:$CI_COMMIT_SHA -t ${IMAGE_NAME}:${TAG} ${CONTEXT}
    - docker push ${IMAGE_NAME}:${CI_COMMIT_SHA}
    - docker push ${IMAGE_NAME}:${TAG}

#
