---
#
variables:
  # CI variables
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  GIT_STRATEGY: fetch

#

stages:
  - "Registration"

#

.register_stage: &register_stage
  stage: "Registration"
  dependencies: []
  image: docker:$DOCKER_VERSION
  services:
    - docker:$DOCKER_VERSION-dind
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
  script:
    - echo "> docker build --pull --cache-from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA -t $IMAGE_NAME:$CI_COMMIT_SHA $CONTEXT"
    - >-
      docker build
        --pull
        --cache-from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA
        --cache-from $IMAGE_NAME:$CI_COMMIT_REF_SLUG
        -t $IMAGE_NAME:$CI_COMMIT_SHA
        $CONTEXT
    - >-
      docker build
        --pull
        --cache-from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA
        --cache-from $IMAGE_NAME:$CI_COMMIT_REF_SLUG
        -t $IMAGE_NAME:$CI_COMMIT_REF_SLUG
        $CONTEXT
    - docker push $IMAGE_NAME

#

Register k8s-object-killer image:
  <<: *register_stage
  variables:
    CONTEXT: images/k8s-object-killer
    IMAGE_NAME: $CI_REGISTRY_IMAGE/k8s-object-killer
