---
#
variables:
  # CI variables
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  GIT_STRATEGY: fetch

  DOCKER_VERSION: "18"

#

stages:
  - "Code Quality"
  - "Registration"

#
#
#

.code_quality_stage: &code_quality_stage
  stage: "Code Quality"
  dependencies: []

#

Test k8s-object-killer:
  <<: *code_quality_stage
  image: python:3.7
  before_script:
    - cd images/k8s-object-killer/killer
    - pip install --no-cache-dir --trusted-host pypi.python.org pipenv
  script:
    # Kind of "pipenv sync --system --dev"
    - pipenv install --ignore-pipfile --system --deploy --dev
    - pipenv run lint
    - pipenv run pretty-check
    - pipenv run type-check

#
#
#

.register_stage: &register_stage
  stage: "Registration"
  dependencies: []
  image: docker:$DOCKER_VERSION
  services:
    - docker:$DOCKER_VERSION-dind
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
  script:
    - >
      if [[ -n "${CI_COMMIT_TAG}" ]]; then
        export TAG=$(printf "${CI_COMMIT_TAG}" | sed "s/^v//")
      else
        export TAG=$CI_COMMIT_REF_SLUG
      fi
    #
    - docker pull $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA || true
    - docker pull $IMAGE_NAME:$TAG || true
    - echo "> docker build --cache-from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA --cache-from $IMAGE_NAME:$TAG -t $IMAGE_NAME:$CI_COMMIT_SHA $CONTEXT"
    - docker build --cache-from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA --cache-from $IMAGE_NAME:$TAG -t $IMAGE_NAME:$CI_COMMIT_SHA $CONTEXT
    - docker build --cache-from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA --cache-from $IMAGE_NAME:$TAG -t $IMAGE_NAME:$TAG $CONTEXT
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME:$TAG

#

Register k8s-object-killer image:
  <<: *register_stage
  variables:
    CONTEXT: images/k8s-object-killer
    IMAGE_NAME: $CI_REGISTRY_IMAGE/k8s-object-killer
