.change_rules_bats:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - &changes_bats
      changes:
        - .gitlab-ci.yml
        - bats/**/*

Lint bats:
  stage: "Quality"
  extends: .change_rules_bats
  image: hadolint/hadolint:v2.3.0-debian
  script:
    - hadolint ./bats/Dockerfile

Build bats:
  stage: "Build"
  needs:
    - Lint bats
  extends:
    - .base_register_to_gitlab_stage
    - .change_rules_bats
  variables:
    CONTEXT: bats
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/bats

Test bats:
  stage: "Test"
  extends: .change_rules_bats
  # NOTE(douglasduteil): retry the whole job
  # In cases when the bats test fails due to heavy load, it's safer to retry agin
  retry: 2
  needs:
    - Lint bats
    - Build bats
  image: "${CI_REGISTRY_IMAGE}/bats:${CI_COMMIT_SHA}"
  script:
    - bats --version
    - bats -p /opt/bats/test/fixtures/bats/passing.bats 
    - bats /opt/bats/test
    - bats /usr/lib/bats-assert/test
    # - bats /usr/lib/bats-file/test
    - bats /usr/lib/bats-support/test
    - bats ./bats/test

Publish bats to Github Registry:
  extends: .base_publish_to_github_stage
  rules:
    - <<: *changes_bats
      if: "$CI_COMMIT_TAG"
  needs:
    - Lint bats
    - Build bats
    - Test bats
  variables:
    IMAGE_NAME: socialgouv/docker/bats
