services:
  alpine:
    build:
      context: .
    deploy:
      replicas: 0
  #

  lint:
    image: ghcr.io/hadolint/hadolint:v2.8.0-alpine
    entrypoint: hadolint
    command: Dockerfile
    volumes:
      - .:/home/socialgouv
    working_dir: /home/socialgouv

  #

  test:
    image: gcr.io/gcp-runtimes/container-structure-test:v1.11.0
    depends_on:
      - alpine
    command: >
      test
      --config tests/container-structure-test.yml
      --image ${COMPOSE_PROJECT_NAME}_alpine
      -v debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/home/socialgouv
    working_dir: /home/socialgouv
