.change_rules_fluentd_modsecurity:
  rules:
    - changes:
        - fluentd-modsecurity/*

Lint fluentd-modsecurity:
  stage: "Quality"
  extends: .change_rules_fluentd_modsecurity
  image: hadolint/hadolint:v1.17.6-debian
  script:
    - hadolint ./fluentd-modsecurity/Dockerfile

Build fluentd-modsecurity:
  stage: "Build"
  needs:
    - Lint fluentd-modsecurity
  extends:
    - .base_register_to_gitlab_stage
    - .change_rules_fluentd_modsecurity
  variables:
    CONTEXT: fluentd-modsecurity
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/fluentd-modsecurity

Test fluentd-modsecurity:
  stage: "Test"
  extends: .change_rules_fluentd_modsecurity
  needs:
    - Lint fluentd-modsecurity
    - Build fluentd-modsecurity
  image: "${CI_REGISTRY_IMAGE}/fluentd-modsecurity:${CI_COMMIT_SHA}"
  script:
    - fluentd --version
    - fluent-gem list

# todo: change_rules should be applied too, but incompatible with only?
# error: jobs:publish fluentd-modsecurity to github registry config key may not be used with `rules`: only
Publish fluentd-modsecurity to Github Registry:
  extends: .base_publish_to_github_stage
  needs:
    - Lint fluentd-modsecurity
    - Build fluentd-modsecurity
  variables:
    IMAGE_NAME: socialgouv/docker/fluentd-modsecurity
