#!/bin/sh

die () { echo "$@" ; cleanup ; exit 1; }
cleanup () {
  rm -rf /tmp/azuredb_test_export_from_k8s_secret_*

  unset -f die cleanup
  unset FOO BAR VALUE_FILE
}

\. ../bin/export_from_k8s_secret

VALUE_FILE=$(mktemp -u /tmp/azuredb_test_export_from_k8s_secret_XXXXXX)
# NOTE(douglasduteil): make a sourcable file with FOO and BAR
# The file should be like :
#
# ```bash
# export FOO="foo value"
# export BAR="bar value"
# ```
#
cat ./setup_dir/fixtures/secret.json | export_from_k8s_secret > ${VALUE_FILE}
source ${VALUE_FILE}

[[ "_$FOO" = "_foo value" ]] || \
die "'export_from_k8s_secret' should export FOO variable" \
  "expected '$FOO', got '_foo value'"
[[ "_$BAR" = "_bar value" ]] || \
die "'export_from_k8s_secret' should export FOO variable" \
  "expected '$BAR', got '_bar value'"

cleanup
