#!/bin/sh

die () { echo "$@" ; cleanup ; exit 1; }
cleanup () {
  rm -rf /tmp/azuredb_test_export_from_k8s_secret_*

  unset -f die cleanup
  unset FOO BAR VALUE_FILE
}

EXPORT_FROM_K8S_SECRET_ENV=testing \. ../bin/export_from_k8s_secret

# NOTE(douglasduteil): stream output with FOO and BAR
# The file should be like :
#
# ```bash
# export FOO="foo value"
# export BAR="bar value"
# ```
#
export_from_k8s_secret < ./setup_dir/fixtures/secret.json  > /tmp/secret && \. /tmp/secret

[ "_$BAR" = "_bar value" ] || \
die "'export_from_k8s_secret' should export BAR variable" \
  "expected '$BAR', got '_bar value'"
[ "_$FOO" = "_foo value" ] || \
die "'export_from_k8s_secret' should export FOO variable" \
  "expected '$FOO', got '_foo value'"
[ "_$PASSWORD" = "_bad\`!(){]|-_$^*@string" ] || \
die "'export_from_k8s_secret' should export PASSWORD variable" \
  "expected '$PASSWORD', got '_bad\`!(){]|-_$^*@string'"

cleanup
