.change_rules_kosko:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - &changes_kosko
      changes:
        - kosko/**/*

Lint kosko:
  stage: "Quality"
  extends: .change_rules_kosko
  image: hadolint/hadolint:v1.18.1-debian
  script:
    - hadolint ./kosko/Dockerfile

Build kosko:
  stage: "Build"
  needs:
    - Lint kosko
  extends:
    - .base_register_to_gitlab_stage
    - .change_rules_kosko
  variables:
    CONTEXT: kosko
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/kosko

Test kosko:
  stage: "Test"
  extends: .change_rules_kosko
  needs:
    - Lint kosko
    - Build kosko
  image: "${CI_REGISTRY_IMAGE}/kosko:${CI_COMMIT_SHA}"
  environment: feature-dev2
  script:
    - kubectl version
    - kubectl cluster-info
    - kustomize version
    - kosko --version
    #
    # bash >=5 test
    - "[[ $(kubectl version) ]] && echo '[[ <test> ]] && <struff>' should be supported"
    - envsubst --version

Publish kosko to Github Registry:
  extends: .base_publish_to_github_stage
  rules:
    - <<: *changes_kosko
      if: "$CI_COMMIT_TAG"
  needs:
    - Lint kosko
    - Build kosko
  variables:
    IMAGE_NAME: socialgouv/docker/kosko
