.change_rules_kaniko:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - &changes_kaniko
      changes:
        - .gitlab-ci.yml
        - kaniko/**/*

Lint kaniko:
  stage: "Quality"
  extends: .change_rules_kaniko
  image: hadolint/hadolint:v1.19.0-debian
  script:
    - hadolint ./kaniko/Dockerfile

Build kaniko:
  stage: "Build"
  extends:
    - .base_register_to_gitlab_stage
    - .change_rules_kaniko
  needs:
    - Lint kaniko
  variables:
    CONTEXT: kaniko
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/kaniko

Test kaniko 1 1:
  needs:
    - Lint kaniko
    - Build kaniko
  stage: "Test"
  extends: .change_rules_kaniko
  image: "${CI_REGISTRY_IMAGE}/kaniko:${CI_COMMIT_SHA}"
  script:
    #
    - kaniko version
    - executor version

Test kaniko 1 2:
  needs:
    - Lint kaniko
    - Build kaniko
  stage: "Test"
  extends: .change_rules_kaniko
  image: "${CI_REGISTRY_IMAGE}/kaniko:${CI_COMMIT_SHA}"
  script:
    #
    - kaniko
      --context dir:///${PWD}/kaniko
      --no-push
      --verbosity trace

Publish kaniko to Github Registry:
  extends: .base_publish_to_github_stage
  rules:
    - <<: *changes_kaniko
      if: "$CI_COMMIT_TAG"
  needs:
    - Lint kaniko
    - Build kaniko
    - Test kaniko 1 1
    - Test kaniko 1 2
  variables:
    IMAGE_NAME: socialgouv/docker/kaniko
