Lint helm:
  stage: "Quality"
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint ./helm/Dockerfile

Build helm:
  allow_failure: true
  stage: "Build"
  needs:
    - Lint helm
  extends: .base_register_to_gitlab_stage
  variables:
    CONTEXT: helm
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/helm

Test helm:
  allow_failure: true
  stage: "Test"
  needs:
    - Lint helm
    - Build helm
  image: "${CI_REGISTRY_IMAGE}/helm:${CI_COMMIT_SHA}"
  environment: feature-dev
  script:
    - helm version
    - kubectl version
    #
    - helm list

Publish helm to Github Registry:
  allow_failure: true
  extends: .base_publish_to_github_stage
  needs:
    - Lint helm
    - Test helm
    - Build helm
  variables:
    IMAGE_NAME: socialgouv/docker/helm
