#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

STAGED_FILES=$(git diff --cached --name-only)

staged_match () {
  echo "${STAGED_FILES}" | grep -E "${1}"
}

dhall_freeze() {
  # Ensure to freeze all imports
  local file="${1}"

  # Ensure to have a cache folder for dhall
  mkdir -p .cache

  echo "$ dhall lint --transitive ${file}"
  docker container run \
    --rm \
    --volume "$(pwd)":"/home/socialgouv" \
    socialgouv/docker/dhall \
    dhall lint --transitive "${file}"

  echo "$ dhall freeze --all --inplace ${file}"
  docker container run \
    --rm \
    --volume "$(pwd)":"/home/socialgouv" \
    socialgouv/docker/dhall \
    dhall freeze --all --transitive "${file}"

  git add "${file}"
}

dhall_to_yaml() {
  # Convert Dhall to Gitlab Action YAML
  local file="${1}"

  workflow=".github/workflows/${file%%/*}.$(basename ${file%.*}).yaml"

  # Ensure to have a cache folder for dhall
  mkdir -p .cache

  echo "$ dhall-to-yaml --file ${file} --output ${workflow}"
  docker container run \
    --rm \
    --volume "$(pwd)":"/home/socialgouv" \
    socialgouv/docker/dhall \
    dhall-to-yaml --file "${file}" --output "${workflow}"

  git add "${workflow}"
}

#
#
#

if staged_match ".*\.dhall$"
then
  # Ensure to have a dhall image ready if a dhall file has changed
  docker build -t socialgouv/docker/dhall dhall
fi

for file in $(staged_match "\.github\/dhall\/.*\.dhall$"); do
  # Freeze changed ".github/dhal/**" dhall files
  dhall_freeze "${file}"
done

workflow_files=".*/\.github/.*\.workflow\.dhall$"
if staged_match "\.github\/dhall\/.*\.dhall$"
then
  # Freeze and regenerate all "*.workflow.dhall" dhall files if the line changes
  find * -name "*.workflow.dhall" -not -path "*/node_modules/*" -type f -print |
  while read file;
  do
    dhall_freeze "${file}"
    dhall_to_yaml "${file}"
  done
else
  # Freeze and regenerate each changed file
  for file in $(staged_match "${workflow_files}"); do
    dhall_freeze "${file}"
    dhall_to_yaml "${file}"
  done
fi
