.change_rules_azure_cli:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - &changes_azure_cli
      changes:
        - .gitlab-ci.yml
        - azure-cli/**/*

Lint azure-cli:
  stage: "Quality"
  extends: .change_rules_azure_cli
  image: hadolint/hadolint:v2.3.0-debian
  script:
    - hadolint ./azure-cli/Dockerfile

Build azure-cli:
  stage: "Build"
  needs:
    - Lint azure-cli
  extends:
    - .base_register_to_gitlab_stage
    - .change_rules_azure_cli
  variables:
    CONTEXT: azure-cli
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/azure-cli

Test azure-cli:
  stage: "Test"
  extends: .change_rules_azure_cli
  needs:
    - Lint azure-cli
    - Build azure-cli
  image: "${CI_REGISTRY_IMAGE}/azure-cli:${CI_COMMIT_SHA}"
  script:
    - az --version

Publish azure-cli to Github Registry:
  extends: .base_publish_to_github_stage
  rules:
    - <<: *changes_azure_cli
      if: "$CI_COMMIT_TAG"
  needs:
    - Lint azure-cli
    - Test azure-cli
    - Build azure-cli
  variables:
    IMAGE_NAME: socialgouv/docker/azure-cli
