name: "Release"
on:
  push:
    branches:
      - master
      - next
      - next-major
      - beta
      - alpha
      - "+([0-9])?(.{+([0-9]),x}).x"
  workflow_run:
    workflows: ["azure-cli (main)"]
    types:
      - completed

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for other checks to succeed
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.ref }}
          running-workflow-name: "release"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 3600
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
