jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        with:
          token: "${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}"
      - env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GIT_AUTHOR_EMAIL: "${{ secrets.SOCIALGROOVYBOT_EMAIL }}"
          GIT_AUTHOR_NAME: "${{ secrets.SOCIALGROOVYBOT_NAME }}"
          GIT_COMMITTER_EMAIL: "${{ secrets.SOCIALGROOVYBOT_EMAIL }}"
          GIT_COMMITTER_NAME: "${{ secrets.SOCIALGROOVYBOT_NAME }}"
        name: Semantic Release
        uses: "cycjimmy/semantic-release-action@v2"
        with:
          extra_plugins: |2
              @semantic-release/changelog
              @semantic-release/exec
              @semantic-release/git
name: Release
on:
  push:
    branches:
      - master
      - next
      - next-major
      - beta
      - alpha
      - "+([0-9])?(.{+([0-9]),x}).x"
