concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.ref }}-${{ github.event_name }}
jobs:
  build:
    uses: ./.github/workflows/workflow.build.yaml
    with:
      name: bats

  version_test:
    needs: [build]
    container: "docker://ghcr.io/socialgouv/docker/bats:sha-${{ github.sha }}"
    name: Test Version
    runs-on: ubuntu-latest
    steps:
      - run: bats --version
name: "bats"
on:
  push:
    tags:
      - bats@**
