name: bats

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    container:
      image: hadolint/hadolint:v1.22.1-alpine
    steps:
      - id: skip_check
        if: |
          !contains(
            'refs/heads/master,refs/heads/beta,refs/heads/next,refs/heads/alpha',
            github.ref
          )
          &&
          !startsWith(github.event.ref, 'refs/tags/v')
        uses: fkirc/skip-duplicate-actions@v3.3.0
        with:
          concurrent_skipping: "same_content"
          paths: |
            [
              "bats/**",
              ".github/workflows/bats.yaml"
            ]
      - uses: actions/checkout@v2
      - run: hadolint ./Dockerfile
        working-directory: bats

  Build:
    runs-on: ubuntu-latest
    needs:
      - Lint
    if: ${{ needs.Lint.outputs.should_skip != 'true' }}
    outputs:
      digest: ${{ steps.docker_meta.outputs.version }}
    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ghcr.io/socialgouv/docker/bats
          label-custom: |
            org.opencontainers.image.title=bats
            org.opencontainers.image.documentation=${{ github.sha }}/bats
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
          tag-sha: true
          tag-custom: sha-${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Login to Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          password: ${{ secrets.GHCR_REGISTRY_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Push
        id: docker_push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: ./bats
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}

      - name: Image digest
        run: |
          echo "${{ steps.docker_push.outputs.digest }}"

  Test:
    runs-on: ubuntu-latest
    needs:
      - Build
    container:
      image: docker://ghcr.io/socialgouv/docker/bats:sha-${{ github.sha }}
    # NOTE(douglasduteil): fix tput for tty issue work around
    # see https://github.com/bats-core/bats-core/blob/v1.3.0/.github/workflows/tests.yml#L30-L31
    env:
      TERM: linux
    steps:
      - name: Version
        run: |
          bats --version
      - name: Dummy test
        run: |
          bats -p /opt/bats/test/fixtures/bats/passing.bats
      - name: Internal
        run: |
          bats /opt/bats/test
      - name: Assert
        run: |
          bats /usr/lib/bats-assert/test
      - name: File
        run: |
          bats /usr/lib/bats-file/test
      - name: Support
        run: |
          bats /usr/lib/bats-support/test
      - name: Kitchen sink
        run: |
          bats ./bats/test
