concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.ref }}-${{ github.event_name }}
jobs:
  build:
    uses: ./.github/workflows/workflow.build.yaml
    secrets: inherit
    with:
      name: cnpg-pgvector

name: "check-cluster-images"
on:
  push:
    tags:
      - "check-cluster-images@**"
