name: CUrl

on:
  push:
    paths:
      - .github/workflows/curl.yaml
      - curl/**
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    container:
      image: hadolint/hadolint:v1.22.1-alpine
    steps:
      - uses: actions/checkout@v2
      - run: hadolint ./Dockerfile
        working-directory: curl

  Build:
    runs-on: ubuntu-latest
    needs:
      - Lint
    outputs:
      digest: ${{ steps.docker_meta.outputs.version }}
    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ghcr.io/socialgouv/docker/curl
          label-custom: |
            org.opencontainers.image.title=CUrl
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
          tag-sha: true
          tag-custom: sha-${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Login to Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          password: ${{ secrets.GHCR_REGISTRY_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Push
        id: docker_push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: ./curl
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}

      - name: Image digest
        run: |
          echo "${{ steps.docker_push.outputs.digest }}"

  Test:
    runs-on: ubuntu-latest
    needs:
      - Build
    container:
      image: docker://ghcr.io/socialgouv/docker/curl:sha-${{ github.sha }}
    steps:
      - name: Version
        run: |
          curl --version
