
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.ref }}-${{ github.event_name }}
jobs:
  build:
    uses: ./.github/workflows/workflow.build.yaml
    secrets: inherit
    with:
      name: github-backup

  version_test:
    container: "docker://ghcr.io/socialgouv/docker/github-backup:sha-${{ github.sha }}"
    name: Test files
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: git --version
name: "github-backup"
on:
  push:
    tags:
      - "github-backup@**"
