concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.ref }}-${{ github.event_name }}
jobs:
  build:
    uses: ./.github/workflows/workflow.build.yaml
    secrets: inherit
    with:
      name: s3-client

  version_test:
    container: "docker://ghcr.io/socialgouv/docker/greenmask:sha-${{ github.sha }}"
    name: Test Version
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: greenmask --version

name: "s3-client"
on:
  push:
    branches:
      - "**"
      - "!master"
      - "!alpha"
      - "!beta"
    paths:
      - "greenmask/**"
      - ".github/workflows/greenmask.yaml"
      - ".github/workflows/greenmask.tag.yaml"
      - ".github/workflows/workflow.build.yaml"
