concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.ref }}-${{ github.event_name }}
jobs:
  build:
    uses: ./.github/workflows/workflow.build.yaml
    secrets: inherit
    with:
      name: greenmask

  version_test:
    container: "docker://ghcr.io/socialgouv/docker/s3-client:sha-${{ github.sha }}"
    name: Test Version
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: greenmask --version

name: "s3-client"
on:
  push:
    tags:
      - "greenmask@**"
