concurrency:
  cancel-in-progress: true
  group: "nginx4spa-${{ github.ref }}"
jobs:
  build:
    name: Build
    needs:
      - Lint
    outputs:
      digest: "${{ steps.docker_push.outputs.digest }}"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - id: docker_meta
        uses: "crazy-max/ghaction-docker-meta@f6efe56d565add159ad605568120f5b22712a870"
        with:
          images: ghcr.io/socialgouv/docker/nginx4spa
          labels: |
            org.opencontainers.image.title=nginx4spa
            org.opencontainers.image.documentation=https://github.com/SocialGouv/docker/tree/${{ github.sha }}/nginx4spa
          tags: |
            type=sha
            type=raw,value=sha-${{ github.sha }}
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=nginx4spa@(.*),group=1
      - id: docker_buildx
        name: Set up Docker Buildx
        uses: "docker/setup-buildx-action@abe5d8f79a1606a2d3e218847032f3f2b1726ab0"
        with: {}
      - if: "${{ github.event_name != 'pull_request' }}"
        name: Login to ghcr.io/socialgouv Registry
        uses: "docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9"
        with:
          password: "${{ secrets.GHCR_REGISTRY_TOKEN }}"
          registry: ghcr.io
          username: "${{ secrets.SOCIALGROOVYBOT_NAME }}"
      - id: docker_push
        name: Push
        uses: "docker/build-push-action@1bc1040caef9e604eb543693ba89b5bf4fc80935"
        with:
          builder: "${{ steps.docker_buildx.outputs.name }}"
          cache-from: type=gha
          cache-to: "type=gha,mode=max"
          context: "./nginx4spa"
          labels: "${{ steps.docker_meta.outputs.labels }}"
          push: 'true'
          tags: "${{ steps.docker_meta.outputs.tags }}"
      - name: Image digest
        run: |
          echo "${{ steps.docker_push.outputs.digest }}"
  integration_test:
    name: Integration test
    needs:
      - Build
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - run: yarn --immutable
      - run: make e2e
        working-directory: nginx4spa
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - uses: "docker://ghcr.io/hadolint/hadolint:2.4.0@sha256:ed22c9de9b884383094edb8930696a256c4450335945c68153d8fc8fbb27bf03"
        with:
          args: hadolint ./nginx4spa/Dockerfile
  security_scan:
    name: Vulnerability Scanner
    needs:
      - Build
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - run: "docker pull ghcr.io/socialgouv/docker/nginx4spa:sha-${{ github.sha }}"
      - name: Run Trivy vulnerability scanner
        uses: "aquasecurity/trivy-action@dba83feec810c70bacbc4bead308ae1e466c572b"
        with:
          image-ref: "ghcr.io/socialgouv/docker/nginx4spa:sha-${{ github.sha }}"
      - name: Export Trivy Results as sarif
        uses: "aquasecurity/trivy-action@dba83feec810c70bacbc4bead308ae1e466c572b"
        with:
          format: template
          image-ref: "ghcr.io/socialgouv/docker/nginx4spa:sha-${{ github.sha }}"
          output: trivy-results.sarif
          template: "@/contrib/sarif.tpl"
      - name: Change hardcoded Dockerfile path
        run: "sed -i 's/\"uri\": \"Dockerfile\"/\"uri\": \"nginx4spa\\/Dockerfile\"/' trivy-results.sarif"
      - uses: "github/codeql-action/upload-sarif@a3a8231e64d3db0e7da0f3b56b9521dcccdfe412"
        with:
          sarif_file: trivy-results.sarif
  version_test:
    container: "docker://ghcr.io/socialgouv/docker/nginx4spa:sha-${{ github.sha }}"
    name: Test Version
    needs:
      - Build
    runs-on: ubuntu-latest
    steps:
      - run: nginx -version
name: "nginx4spa (branch)"
on:
  push:
    paths:
      - "nginx4spa/**"
      - ".github/workflows/nginx4spa.yaml"
