permissions:
  packages: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.ref }}-${{ github.event_name }}
jobs:
  build:
    uses: ./.github/workflows/workflow.build.yaml
    secrets: inherit
    with:
      name: nginx4spa

  version_test:
    container: "docker://ghcr.io/socialgouv/docker/nginx4spa:sha-${{ github.sha }}"
    name: Test Version
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: nginx -version
name: "nginx4spa"
on:
  push:
    branches:
      - "**"
      - "!master"
      - "!alpha"
      - "!beta"
    paths:
      - "nginx4spa/**"
      - ".github/workflows/nginx4spa.yaml"
      - ".github/workflows/nginx4spa.tag.yaml"
      - ".github/workflows/workflow.build.yaml"
