concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.ref }}-${{ github.event_name }}
jobs:
  build:
    uses: ./.github/workflows/workflow.build.yaml
    secrets: inherit
    with:
      name: wait-for-postgres

  version_test:
    container: "docker://ghcr.io/socialgouv/docker/wait-for-postgres:sha-${{ github.sha }}"
    name: Test Version
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: psql --version
      - run: which wait-for-postgres

name: "wait-for-postgres"
on:
  push:
    branches:
      - "**"
      - "!master"
      - "!alpha"
      - "!beta"
    paths:
      - "wait-for-postgres/**"
      - ".github/workflows/wait-for-postgres.yaml"
      - ".github/workflows/wait-for-postgres.tag.yaml"
      - ".github/workflows/workflow.build.yaml"

